---

- name: jupiter container
  docker_container:
    name: jupiter
    image: jupyter/datascience-notebook:latest
    state: started
    published_ports:
    - "8888:8888"
    pull: no
    restart_policy: on-failure
    restart_retries: 3
    volumes:
    - /opt/serhiy/dbrs/notebook:/home/jovyan/work:rw
