---

- name: run the playbook tasks on the localhost
  hosts: 127.0.0.1
  connection: local
  vars:
    docker_edition: 'ce'
    pip_install_packages:
    - name: docker
  roles:
  - geerlingguy.pip
  - geerlingguy.docker
  - run_notebook
